/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aloi.sponto;

import java.awt.event.ActionEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JSplitPane;

import javax.swing.event.AncestorEvent;

/**
 *
 * @author maloi
 */
public class TuQueSabePanel extends javax.swing.JPanel {

    /**
     * Creates new form TuQueSabePanel
     */
    public TuQueSabePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameOptions = new javax.swing.JFrame();
        OnlyFind = new javax.swing.JCheckBox();
        replaceInclude = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        autoProcess = new javax.swing.JCheckBox();
        process = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        groupvalue = new javax.swing.JTextField();
        separetor = new javax.swing.JTextField();
        begin = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        findReplace = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultReplace = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        sOriginal = new javax.swing.JScrollPane();
        original = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        sModifed = new javax.swing.JScrollPane();
        modifed = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        FindBreak = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        ReplaceFind = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        buttonOptions = new javax.swing.JButton();
        buttons = new javax.swing.JPanel();
        colar = new javax.swing.JButton();
        copiar = new javax.swing.JButton();
        exceptionE = new javax.swing.JLabel();

        frameOptions.getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        OnlyFind.setSelected(true);
        OnlyFind.setText("Only Find");
        OnlyFind.setToolTipText("");
        frameOptions.getContentPane().add(OnlyFind);

        replaceInclude.setText("Replace and include what Find");
        frameOptions.getContentPane().add(replaceInclude);

        jPanel10.setLayout(new java.awt.BorderLayout());

        autoProcess.setSelected(true);
        autoProcess.setText("auto");
        autoProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoProcessActionPerformed(evt);
            }
        });
        jPanel10.add(autoProcess, java.awt.BorderLayout.CENTER);

        process.setText("process");
        process.setEnabled(false);
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });
        jPanel10.add(process, java.awt.BorderLayout.EAST);

        frameOptions.getContentPane().add(jPanel10);

        jPanel9.setMinimumSize(new java.awt.Dimension(22, 50));
        jPanel9.setLayout(new java.awt.GridLayout(2, 2));

        groupvalue.setToolTipText("Group List");
        jPanel9.add(groupvalue);

        separetor.setToolTipText("Separator");
        jPanel9.add(separetor);

        begin.setBackground(new java.awt.Color(247, 247, 245));
        begin.setToolTipText("Begin group");
        jPanel9.add(begin);

        end.setBackground(new java.awt.Color(247, 247, 245));
        end.setToolTipText("End group");
        jPanel9.add(end);

        frameOptions.getContentPane().add(jPanel9);

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        frameOptions.getContentPane().add(jButton3);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jSplitPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSplitPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSplitPane1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jSplitPane1AncestorResized(evt);
            }
        });

        findReplace.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        findReplace.setText("[\\d]{10}");
        findReplace.setToolTipText("Text do you like find with regex ");
        findReplace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(findReplace);

        jSplitPane1.setLeftComponent(jScrollPane3);

        resultReplace.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        resultReplace.setText("n0");
        resultReplace.setToolTipText("Only used in replace of text");
        resultReplace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(resultReplace);

        jSplitPane1.setRightComponent(jScrollPane4);

        jPanel1.add(jSplitPane1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(400);
        jSplitPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSplitPaneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSplitPane.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jSplitPaneAncestorResized(evt);
            }
        });

        original.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        original.setLineWrap(true);
        original.setWrapStyleWord(true);
        sOriginal.setViewportView(original);

        jSplitPane.setLeftComponent(sOriginal);
        jSplitPane.setRightComponent(jSeparator1);

        modifed.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        modifed.setLineWrap(true);
        modifed.setWrapStyleWord(true);
        sModifed.setViewportView(modifed);

        jSplitPane.setRightComponent(sModifed);

        jPanel2.add(jSplitPane, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        FindBreak.setText("Break Line");
        jPanel3.add(FindBreak);
        jPanel3.add(jPanel6);

        ReplaceFind.setText("Replace what Find");
        jPanel3.add(ReplaceFind);

        jButton4.setLabel("saved");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        buttonOptions.setLabel("options");
        buttonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionsActionPerformed(evt);
            }
        });
        jPanel3.add(buttonOptions);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        buttons.setLayout(new java.awt.GridLayout(1, 2));

        colar.setText("colar");
        colar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colarActionPerformed(evt);
            }
        });
        buttons.add(colar);

        copiar.setText("copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        buttons.add(copiar);

        jPanel4.add(buttons, java.awt.BorderLayout.NORTH);

        exceptionE.setToolTipText("");
        jPanel4.add(exceptionE, java.awt.BorderLayout.SOUTH);

        add(jPanel4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    protected void jSplitPaneAncestorResized(HierarchyEvent evt) {
        jSplitPaneAncestorResized(evt,jSplitPane);
    }

    protected void jSplitPaneAncestorAdded(AncestorEvent evt) {
        jSplitPaneAncestorAdded(evt,jSplitPane);
    }

    protected void jSplitPane1AncestorResized(HierarchyEvent evt) {
        jSplitPaneAncestorResized(evt,jSplitPane1);
    }

    protected void jSplitPane1AncestorAdded(AncestorEvent evt) {
        jSplitPaneAncestorAdded(evt,jSplitPane1);
    }

    protected void copiarActionPerformed(ActionEvent evt) {
    }

    protected void colarActionPerformed(ActionEvent evt) {
    }

    protected void jButton4ActionPerformed(ActionEvent evt) {
    }



    private void jSplitPaneAncestorAdded(javax.swing.event.AncestorEvent evt,JSplitPane jSplitPaneInternal) {                                          
        jSplitPaneInternal.setDividerLocation(getSize().width / 2);
    }                                         

    private void jSplitPaneAncestorResized(java.awt.event.HierarchyEvent evt,JSplitPane jSplitPaneInternal) {                                            
        jSplitPaneInternal.setDividerLocation(getSize().width / 2);
    } 

    protected void jButton2ActionPerformed(ActionEvent evt) {
    }

    protected void jButton1ActionPerformed(ActionEvent evt) {
    }

    protected void jList1MouseClicked(MouseEvent evt) {
    }

    protected void jButton3ActionPerformed(ActionEvent evt) {
    }

    protected void processActionPerformed(ActionEvent evt) {
    }

    protected void autoProcessActionPerformed(ActionEvent evt) {
    }

    private void buttonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionsActionPerformed
        frameOptions.setVisible(true);
    }//GEN-LAST:event_buttonOptionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FindBreak;
    private javax.swing.JCheckBox OnlyFind;
    private javax.swing.JCheckBox ReplaceFind;
    private javax.swing.JCheckBox autoProcess;
    private javax.swing.JTextField begin;
    private javax.swing.JButton buttonOptions;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton colar;
    private javax.swing.JButton copiar;
    private javax.swing.JTextField end;
    private javax.swing.JLabel exceptionE;
    protected javax.swing.JTextArea findReplace;
    private javax.swing.JFrame frameOptions;
    private javax.swing.JTextField groupvalue;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea modifed;
    private javax.swing.JTextArea original;
    private javax.swing.JButton process;
    private javax.swing.JCheckBox replaceInclude;
    protected javax.swing.JTextArea resultReplace;
    private javax.swing.JScrollPane sModifed;
    private javax.swing.JScrollPane sOriginal;
    private javax.swing.JTextField separetor;
    // End of variables declaration//GEN-END:variables
}
